import { HandleRedirect } from 'components/handle-redirect';
import { Layout } from 'components/layout';
import { useAppSelector } from 'hooks/use-app-selector';
import type { NextPage } from 'next';
import Head from 'next/head';
import { selectUser } from 'store/slices/user-slice';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const user = useAppSelector(selectUser);

  return (
    <HandleRedirect userTo="/authenticated" fullPageLoader>
      <Layout>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <ul>
            <li>
              if user is authenticated, he should <em>not</em> see this page.
            </li>
            <li>
              If you hard reload the page, a full page loading spinner should
              appear without flush.
            </li>
            <li>
              After loading is completed, page content should show up without
              flush.
            </li>
          </ul>

          <hr />

          <h1>
            I am{' '}
            <span style={{ color: 'red' }}>
              not authenticated: {(!user.data).toString()}
            </span>
          </h1>
        </div>
      </Layout>
    </HandleRedirect>
  );
};

export default Home;
